### ISSUE TITLE
digitransit.fi redirects to reittiopas.hsl.fi

### ISSUE THREAD

**Issue by datarttu** [HSLdevcom/digitransit-site#207]
Digitransit.fi seems to be unavailable and immediately redirects to reittiopas.hsl.fi. [digitransit.fi/en/developers](https://digitransit.fi/en/developers) redirects to Reittiopas as well, setting `developers` as the search keyword. Is something broken, or has the Digitransit documentation been moved elsewhere?

**Comment by optionsome** [comment]
Yes sorry. Something was indeed broken for 1.5ish hours, but it's now fixed. Unfortunately the broken redirect might persist on the browser for a while...

**Comment by datarttu** [comment]
Seems to work now. Many thanks!
